name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Setup DVC remote auth
        run: |
          dvc remote modify dagshub auth basic
          dvc remote modify dagshub user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify dagshub password ${{ secrets.DAGSHUB_PAT }}
      - name: Pull DVC data
        run: |
          dvc pull --force
      - name: run dvc repro
        run: |
          dvc repro
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username : ${{secrets.DOCKER_USER_NAME}}
          password : ${{secrets.DOCKER_PAT}}
      - name: Docker build image
        run: |
          docker build -t ${{secrets.DOCKER_USER_NAME}}/loanapproval:latest .
      - name: push docker image to docker hub
        run: |
          docker push ${{secrets.DOCKER_USER_NAME}}/loanapproval:latest

      - name: Deploy to amazon ec2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
              docker pull ${{secrets.DOCKER_USER_NAME}}/loanapproval:latest
              docker stop my-app || true
              docker rm my-app || true
              docker run -d -p 80:8501 \
                --name my-app \
                -e DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }} \
                -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
                ${{secrets.DOCKER_USER_NAME}}/loanapproval:latest
          
